fixtures:
  repositories:
    augeas_core: 'git://github.com/puppetlabs/puppetlabs-augeas_core'
    concat: 'git://github.com/puppetlabs/puppetlabs-concat'
    openssl: 'git://github.com/camptocamp/puppet-openssl'
    stdlib: 'git://github.com/puppetlabs/puppetlabs-stdlib'
    vcsrepo: 'git://github.com/puppetlabs/puppetlabs-vcsrepo'
  symlinks:
    'acme': "#{source_dir}"
